# `guard case`

Mike.

# Pointâ€‘Free

https://www.pointfree.co/

# `defer` is not quite a closure (Dave)
`defer { }` is a great feature of Swift for ensuring a piece of code is executed just before your function completes (returns or throws). It takes a closure that is invoked upon completion.

However, say I want to be able to print matching entry and exit values for a variable:
```swift
func myFunc() {
  var val = 1
  Log.entry("val=\(val)")
  defer {
    Log.exit("val=\(val)")
  }
  // Do some stuff
  val = -1
}

class Log {
  static func entry(_ msg: String, fun: String = #function) {
    print("ENTRY: \(fun): \(msg)")
  }
  static func exit(_ msg: String, fun: String = #function) {
    print("EXIT: \(fun): \(msg)")
  }
}

myFunc()
```
Running the above code results in
```
ENTRY: myFunc(): val=1
EXIT: myFunc(): val=-1
```
The reference to `var` was captured, not the value. With standard closure syntax, I should be able to change this to:
```swift
  defer { [val] in
    Log.exit("val=\(val)")
  }
```
...but it does not compile:
```
defer.swift:4:16: error: consecutive statements on a line must be separated by ';'
  defer { [val] in
               ^
               ;
defer.swift:4:17: error: expected expression
  defer { [val] in
                ^
defer.swift:4:11: warning: expression of type '[Int]' is unused
  defer { [val] in
          ^~~~~
```
But it seems to behave like a closure in other respects. If I move the declaration of `var` to later in the function:
```swift
func myFunc() {
  defer {
    Log.exit("val=\(val)")
  }
  var val = 1
  Log.entry("val=\(val)")
  // Do some stuff
  val = -1
}
```
...the compiler states:
```
defer.swift:3:21: error: cannot capture 'val' before it is declared
    Log.exit("val=\(val)")
                    ^
defer.swift:5:7: note: 'val' declared here
  var val = 1
      ^
```
Perhaps the syntax for a defer closure is deliberately restricted?
